painting:
  importFilesPath: C:\Users
  importPaintingPath: C:\Users
  wildCard: '*{name}.png;*{name}_dec.png;*{name}_group.png;*{name}_exp.png'
paintingface:
  ApplyCorrection: true
  importFilesPath: C:\Users
  importFace2DPath: C:\Users
  importFaceFilePath: C:\Users
  wildCard_2D: 0.png;{name}_head.png
  wildCard_File: '{name}'
